name: CI Pipeline

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]

jobs:
  frontend:
    name: Frontend CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend-SaaS

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: frontend-SaaS/package-lock.json

      - name: Instalar dependencias
        run: npm ci

      - name: Build
        run: npm run build

  backend:
    name: Backend CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend-SaaS

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: backend-SaaS/package-lock.json

      - name: Instalar dependencias
        run: npm ci

      - name: Build
        run: npm run build